version: '3'
services:
  postgresql:
    image: postgres:10
    container_name: postgresql
    hostname: postgresql-server
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS:--encoding=UTF-8 --locale=C
    restart: always

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    ports:
      - 8000:80
    volumes:
      -  tool-data:/var/lib/pgadmin
    environment:
      - TZ=Asia/Tokyo
      - PGADMIN_DEFAULT_EMAIL=admin@testdomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgresql
    restart: always

volumes:
  db-data:
    driver: local
  tool-data:
    driver: local
